app:
  jwt:
    secret: ${JWT_SECRET}

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/sewalo}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 150MB

cloudinary:
  cloud:
    name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_SECRET_KEY}

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.amqp: DEBUG
    org.springframework.amqp.rabbit: DEBUG
    org.springframework.amqp.rabbit.connection: DEBUG
    com.rabbitmq: DEBUG
    raicod3.example.com: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%clr(%level){withPad}] %msg%n"



