app:
  jwt:
    secret: ${JWT_SECRET}

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sewalo}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
  output:
    ansi:
      enabled: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    org:
      springframework: WARN
      hibernate: WARN
    raicod3.example.com: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%clr(%level){withPad}] %msg%n"
